// import Currency from './Currency';

// const Flags = {};
// Object.keys(Currency).map(function(key){
//     Flags[key] = require('../assets/images/flags/"+  key.toLowerCase() + ".png')"; 
// })

export default {
    "AED": require('../assets/images/flags/aed.png'),
    "AFN": require('../assets/images/flags/afn.png'),
    "ALL": require('../assets/images/flags/all.png'),
    "AMD": require('../assets/images/flags/amd.png'),
    "ARS": require('../assets/images/flags/ars.png'),
    "AUD": require('../assets/images/flags/aud.png'),
    "AZN": require('../assets/images/flags/azn.png'),
    "BAM": require('../assets/images/flags/bam.png'),
    "BDT": require('../assets/images/flags/bdt.png'),
    "BGN": require('../assets/images/flags/bgn.png'),
    "BHD": require('../assets/images/flags/bhd.png'),
    "BIF": require('../assets/images/flags/bif.png'),
    "BND": require('../assets/images/flags/bnd.png'),
    "BOB": require('../assets/images/flags/bob.png'),
    "BRL": require('../assets/images/flags/brl.png'),
    "BWP": require('../assets/images/flags/bwp.png'),
    // "BYR": require('../assets/images/flags/byr.png'),
    "BZD": require('../assets/images/flags/bzd.png'),
    "CAD": require('../assets/images/flags/cad.png'),
    "CDF": require('../assets/images/flags/cdf.png'),
    "CHF": require('../assets/images/flags/chf.png'),
    "CLP": require('../assets/images/flags/clp.png'),
    "CNY": require('../assets/images/flags/cny.png'),
    "COP": require('../assets/images/flags/cop.png'),
    "CRC": require('../assets/images/flags/crc.png'),
    "CVE": require('../assets/images/flags/cve.png'),
    "CZK": require('../assets/images/flags/czk.png'),
    "DJF": require('../assets/images/flags/djf.png'),
    "DKK": require('../assets/images/flags/dkk.png'),
    "DOP": require('../assets/images/flags/dop.png'),
    "DZD": require('../assets/images/flags/dzd.png'),
    // "EEK": require('../assets/images/flags/eek.png'),
    "EGP": require('../assets/images/flags/egp.png'),
    "ERN": require('../assets/images/flags/ern.png'),
    "ETB": require('../assets/images/flags/etb.png'),
    "EUR": require('../assets/images/flags/eur.png'),
    "GBP": require('../assets/images/flags/gbp.png'),
    "GEL": require('../assets/images/flags/gel.png'),
    "GHS": require('../assets/images/flags/ghs.png'),
    "GNF": require('../assets/images/flags/gnf.png'),
    "GTQ": require('../assets/images/flags/gtq.png'),
    "HKD": require('../assets/images/flags/hkd.png'),
    "HNL": require('../assets/images/flags/hnl.png'),
    "HRK": require('../assets/images/flags/hrk.png'),
    "HUF": require('../assets/images/flags/huf.png'),
    "IDR": require('../assets/images/flags/idr.png'),
    "ILS": require('../assets/images/flags/ils.png'),
    "INR": require('../assets/images/flags/inr.png'),
    "IQD": require('../assets/images/flags/iqd.png'),
    "IRR": require('../assets/images/flags/irr.png'),
    "ISK": require('../assets/images/flags/isk.png'),
    "JMD": require('../assets/images/flags/jmd.png'),
    "JOD": require('../assets/images/flags/jod.png'),
    "JPY": require('../assets/images/flags/jpy.png'),
    "KES": require('../assets/images/flags/kes.png'),
    "KHR": require('../assets/images/flags/khr.png'),
    "KMF": require('../assets/images/flags/kmf.png'),
    "KRW": require('../assets/images/flags/krw.png'),
    "KWD": require('../assets/images/flags/kwd.png'),
    "KZT": require('../assets/images/flags/kzt.png'),
    "LBP": require('../assets/images/flags/lbp.png'),
    "LKR": require('../assets/images/flags/lkr.png'),
    "LTL": require('../assets/images/flags/ltl.png'),
    // "LVL": require('../assets/images/flags/lvl.png'),
    "LYD": require('../assets/images/flags/lyd.png'),
    "MAD": require('../assets/images/flags/mad.png'),
    "MDL": require('../assets/images/flags/mdl.png'),
    "MGA": require('../assets/images/flags/mga.png'),
    "MKD": require('../assets/images/flags/mkd.png'),
    "MMK": require('../assets/images/flags/mmk.png'),
    "MOP": require('../assets/images/flags/mop.png'),
    "MUR": require('../assets/images/flags/mur.png'),
    "MXN": require('../assets/images/flags/mxn.png'),
    "MYR": require('../assets/images/flags/myr.png'),
    "MZN": require('../assets/images/flags/mzn.png'),
    "NAD": require('../assets/images/flags/nad.png'),
    "NGN": require('../assets/images/flags/ngn.png'),
    "NIO": require('../assets/images/flags/nio.png'),
    "NOK": require('../assets/images/flags/nok.png'),
    "NPR": require('../assets/images/flags/npr.png'),
    "NZD": require('../assets/images/flags/nzd.png'),
    "OMR": require('../assets/images/flags/omr.png'),
    // "PAB": require('../assets/images/flags/pab.png'),
    "PEN": require('../assets/images/flags/pen.png'),
    "PHP": require('../assets/images/flags/php.png'),
    "PKR": require('../assets/images/flags/pkr.png'),
    "PLN": require('../assets/images/flags/pln.png'),
    "PYG": require('../assets/images/flags/pyg.png'),
    "QAR": require('../assets/images/flags/qar.png'),
    "RON": require('../assets/images/flags/ron.png'),
    "RSD": require('../assets/images/flags/rsd.png'),
    "RUB": require('../assets/images/flags/rub.png'),
    "RWF": require('../assets/images/flags/rwf.png'),
    "SAR": require('../assets/images/flags/sar.png'),
    // "SDG": require('../assets/images/flags/sdg.png'),
    "SEK": require('../assets/images/flags/sek.png'),
    "SGD": require('../assets/images/flags/sgd.png'),
    "SOS": require('../assets/images/flags/sos.png'),
    "SYP": require('../assets/images/flags/syp.png'),
    "THB": require('../assets/images/flags/thb.png'),
    "TND": require('../assets/images/flags/tnd.png'),
    "TOP": require('../assets/images/flags/top.png'),
    "TRY": require('../assets/images/flags/try.png'),
    "TTD": require('../assets/images/flags/ttd.png'),
    "TWD": require('../assets/images/flags/twd.png'),
    "TZS": require('../assets/images/flags/tzs.png'),
    "UAH": require('../assets/images/flags/uah.png'),
    "UGX": require('../assets/images/flags/ugx.png'),
    "USD": require('../assets/images/flags/usd.png'),
    "UYU": require('../assets/images/flags/uyu.png'),
    "UZS": require('../assets/images/flags/uzs.png'),
    "VEF": require('../assets/images/flags/vef.png'),
    "VND": require('../assets/images/flags/vnd.png'),
    "XAF": require('../assets/images/flags/xaf.png'),
    "XOF": require('../assets/images/flags/xof.png'),
    "YER": require('../assets/images/flags/yer.png'),
    "ZAR": require('../assets/images/flags/zar.png'),
};